[project]
name = "generate-notes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mido>=1.3.3",
    "pydub>=0.25.1",
    "pygame>=2.6.1",
    "python-rtmidi>=1.5.8",
]
